### ISSUE TITLE
Describe how to run outside Docker

### ISSUE THREAD

**Issue by anthonyharrison** [javixeneize/neo4cyclone#6]
Describe steps to run outside Docker:

Install neo4j application
Start neo4j server 
pip install -r requirements.txt
python main.py

Go to localhost:7474 and login to database (default user seems to be neo4j/neo4j)

However attempts to ingest the SBOM results in Cannot resolve address neo4j:7687

**Comment by javixeneize** [comment]
Ups, my fault. You need to run ingest_data_neo4j.py and send two parameters, project name and file name
python3 ingest_data_neo4j.py myproject mysbomfile.json

 I will update the documentation 

Thanks for reporting!

**Comment by javixeneize** [comment]
Documentation updated with instructions
